### ISSUE TITLE
writepfb | Unclear function description on coordinate system

### ISSUE THREAD

**Issue by jsacerot** [lecondon/PriorityFlow#1]
Good afternoon,

I would like to know if ```writepfb``` accounts for the indexing difference between R matrices (row, col) and ParFlow binary files (x, y) or if the user needs to transpose/flip the matrix values.

Thank you!

**Comment by lecondon** [comment]
Hi, 

Thank you for checking. The algorithms used here make the following assumption about array format which is noted in the [example](https://github.com/lecondon/PriorityFlow/blob/master/Workflow_Example.Rmd): 
"NOTE: The data sets used here are already formatted as [nx,ny] matrices such that the [i,j] indices correspond to the x and y axes of the domain respectively and [1,1] is the lower left corner and [nx,ny] is the upper right corner. You will need to have your DEM and any other input files formatted like this before you get started. To check that you have them formatted correctly you should be able to do image.plot(yourDEM) and your domain should appear correctly (i.e. untransposed)."

The outputs generated by the DEM processing will be in the correct format for the pfb writer without any transposing. For the record though the format required for the pfb writer is note[ here](https://github.com/lecondon/PriorityFlow/blob/master/Rpkg/R/PFB-WriteFcn.R):
"#' @param to.write The array to be written. This must be a 3D array with dimensions nx, ny, nz.
#'  values should be input to the array such that [1,1,1] is the lower left corner of the domain and [nx,ny,nz] is the upper right"

**Comment by jsacerot** [comment]
Thank you for the clarification, Laura.
